services:
  db:
    image: postgres:15-alpine
    command: postgres -c timezone=UTC
    container_name: loyalty_postgres
    restart: always
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_USER: loyalty_user
      POSTGRES_PASSWORD: loyalty_password
      POSTGRES_DB: loyalty_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loyalty_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loyalty_user -d loyalty_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: loyalty_server
    restart: always
    ports:
      - "8080:8080"
    environment:
      TZ: UTC
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/loyalty_db
      JDBC_DATABASE_USERNAME: loyalty_user
      JDBC_DATABASE_PASSWORD: loyalty_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - loyalty_net

  redis:
    image: redis:alpine
    container_name: loyalty_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: UTC
    networks:
      - loyalty_net

  web-admin:
    build:
      context: .
      dockerfile: web-admin/Dockerfile
    container_name: loyalty_web_admin
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      TZ: UTC
    networks:
      - loyalty_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: loyalty_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@loyalty.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - loyalty_net

volumes:
  postgres_data:

networks:
  loyalty_net:
    driver: bridge