platform :ios, '14.0'
use_frameworks!

def shared_pods
  # Kotlin-фреймворк (внутри фреймворк LoyaltyLoop)
  pod 'composeApp', :path => '../composeApp'
  # Яндекс Карты: версия совпадает с composeApp (4.5.1-lite)
  pod 'YandexMapsMobile', '4.5.1-lite'
end

target 'iosApp' do
  shared_pods
end