server {
    listen 80;
    
    # Включаем сжатие, чтобы сайт грузился быстрее
    gzip on;
    gzip_min_length 1000;
    gzip_types text/plain text/xml application/javascript text/css;

    root /usr/share/nginx/html;
    index index.html;

    # Главная магия SPA:
    # Если файл (картинка, js) найден — отдаем его.
    # Если нет (например, путь /dashboard) — отдаем index.html, пусть React разбирается.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статики (картинок, шрифтов) на год
    location ~* \.(?:jpg|jpeg|gif|png|ico|svg|webp|woff|woff2|ttf|eot)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}