ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ io.loyaltyloop.server.ApplicationKt.module ]
    }
}

storage {
    driverClassName = "org.postgresql.Driver"
    jdbcUrl = "jdbc:postgresql://localhost:5432/loyalty_db"
    jdbcUrl = ${?JDBC_DATABASE_URL}

    user = "loyalty_user"
    user = ${?JDBC_DATABASE_USERNAME}

    password = "loyalty_password"
    password = ${?JDBC_DATABASE_PASSWORD}
}

sms {
    # Главный переключатель: 'console' или 'real' (деньги)
    provider = "console"
    provider = ${?SMS_PROVIDER}

    # Настройки для Кыргызстана (Nikita Online)
    prelude {
            apiKey = "твои_api_key"
            apiKey = ${?PRELUDE_API_KEY}
    }
}

jwt {
    # Секрет шифрования. В проде обязательно переопределить через ENV!
       secret = "e2d7ad2010aa7d52b6cf70b41c6dc65bd7f3497c8d721439a0e823209d474ba0"
       secret = ${?JWT_SECRET}

       # Кто выдал токен. Локально localhost, в проде - ваш домен (https://...)
       issuer = "http://localhost:8080/"
       issuer = ${?JWT_ISSUER}

       # Для кого токен. Обычно совпадает с issuer или просто домен API
       audience = "http://localhost:8080/"
       audience = ${?JWT_AUDIENCE}

       realm = "Access to LoyaltyLoop"

       # 1 час
       accessLifetime = 3600000
       accessLifetime = ${?JWT_ACCESS_LIFETIME}

       # 30 дней
       refreshLifetime = 2592000000
       refreshLifetime = ${?JWT_REFRESH_LIFETIME}
}

otp {
    ttl = 120000
}

admin {
    superUserPhone = "+996554190030"
    defaultPin = "0000"
    defaultPin = ${?ADMIN_DEFAULT_PIN}
    forcePartnerPin = ${?ADMIN_FORCE_PARTNER_PIN}
}

features {
    enableTestSupport = true
    enableTestSupport = ${?FEATURE_TEST_SUPPORT}
    pushEnabled = true
    pushEnabled = ${?FEATURE_PUSH}
    enableSwagger = false
    enableSwagger = ${?FEATURE_ENABLE_SWAGGER}
}

platform {
    managerInviteCode = "SECRET123"
    managerInviteCode = ${?PLATFORM_MANAGER_INVITE}
}

app {
    webBaseUrl = "http://localhost:3000"
    webBaseUrl = ${?WEB_BASE_URL}

    maps {
       defaultLat = 42.8746
       defaultLat = ${?MAP_DEFAULT_LAT}
       defaultLon = 74.5698
       defaultLon = ${?MAP_DEFAULT_LON}
       minRadiusMeters = 50
       minRadiusMeters = ${?MAP_MIN_RADIUS}
       defaultRadiusMeters = 2000
       defaultRadiusMeters = ${?MAP_DEFAULT_RADIUS}
       maxRadiusMeters = 50000
       maxRadiusMeters = ${?MAP_MAX_RADIUS}
       clusterRadiusMeters = 80
       clusterRadiusMeters = ${?MAP_CLUSTER_RADIUS}
       searchDebounceMs = 350
       searchDebounceMs = ${?MAP_SEARCH_DEBOUNCE}
       showRatings = true
       showRatings = ${?MAP_SHOW_RATINGS}
       showWorkingHours = true
       showWorkingHours = ${?MAP_SHOW_HOURS}

    }
}
