ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ io.loyaltyloop.server.ApplicationKt.module ]
    }
}

storage {
    driverClassName = "org.postgresql.Driver"
    jdbcUrl = "jdbc:postgresql://localhost:5432/loyalty_db"
    jdbcUrl = ${?JDBC_DATABASE_URL}

    user = "loyalty_user"
    user = ${?JDBC_DATABASE_USERNAME}

    password = "loyalty_password"
    password = ${?JDBC_DATABASE_PASSWORD}
}

jwt {
    secret = "secret_key_change_me_in_prod"
    secret = ${?JWT_SECRET}
    issuer = "http://0.0.0.0:8080/"
    issuer = ${?JWT_ISSUER}
    audience = "http://0.0.0.0:8080/hello"
    audience = ${?JWT_AUDIENCE}
    realm = "Access to LoyaltyLoop"

    accessLifetime = 3600000
    accessLifetime = ${?JWT_ACCESS_LIFETIME}
    refreshLifetime = 2592000000
    refreshLifetime = ${?JWT_REFRESH_LIFETIME}
}

otp {
    ttl = 120000
}

admin {
    superUserPhone = "+996554190030"
    defaultPin = "0000"
    defaultPin = ${?ADMIN_DEFAULT_PIN}
    forcePartnerPin = ${?ADMIN_FORCE_PARTNER_PIN}
}

features {
    enableTestSupport = true
    enableTestSupport = ${?FEATURE_TEST_SUPPORT}
    realtimeEnabled = true
    realtimeEnabled = ${?FEATURE_REALTIME}
    pushEnabled = true
    pushEnabled = ${?FEATURE_PUSH}
    mapEnabled = true
    mapEnabled = ${?FEATURE_MAP}
    testLabEnabled = false
    testLabEnabled = ${?FEATURE_TEST_LAB}
}

platform {
    managerInviteCode = "SECRET123"
    managerInviteCode = ${?PLATFORM_MANAGER_INVITE}
}

app {
    webBaseUrl = "http://localhost:3000"
    webBaseUrl = ${?WEB_BASE_URL}

    maps {
       defaultLat = 42.8746
       defaultLat = ${?MAP_DEFAULT_LAT}
       defaultLon = 74.5698
       defaultLon = ${?MAP_DEFAULT_LON}
       minRadiusMeters = 50
       minRadiusMeters = ${?MAP_MIN_RADIUS}
       defaultRadiusMeters = 2000
       defaultRadiusMeters = ${?MAP_DEFAULT_RADIUS}
       maxRadiusMeters = 15000
       maxRadiusMeters = ${?MAP_MAX_RADIUS}
       clusterRadiusMeters = 80
       clusterRadiusMeters = ${?MAP_CLUSTER_RADIUS}
       searchDebounceMs = 350
       searchDebounceMs = ${?MAP_SEARCH_DEBOUNCE}
       showRatings = true
       showRatings = ${?MAP_SHOW_RATINGS}
       showWorkingHours = true
       showWorkingHours = ${?MAP_SHOW_HOURS}
        yandexWebKey = "ffb31301-c998-483f-95a7-729f5f29ac1d"
        yandexWebKey = ${?YANDEX_MAPS_WEB_KEY}

    }
}
