ktor {
    deployment {
        port = 8080
        port = ${?PORT} # Если есть переменная PORT, берем её (для Прода)
    }
    application {
        modules = [ io.loyaltyloop.server.ApplicationKt.module ]
    }
}

# Наши настройки базы данных
storage {
    driverClassName = "org.postgresql.Driver"
    # По умолчанию (Dev)
    jdbcUrl = "jdbc:postgresql://localhost:5432/loyalty_db"
    jdbcUrl = ${?JDBC_DATABASE_URL} # В Проде подставим сюда реальный URL

    user = "loyalty_user"
    user = ${?JDBC_DATABASE_USERNAME}

    password = "loyalty_password"
    password = ${?JDBC_DATABASE_PASSWORD}
}