package io.loyaltyloop.shared.models

import kotlinx.serialization.Serializable

enum class AppErrorCode {
    // Common
    SUCCESS,
    UNKNOWN_ERROR,
    INTERNAL_ERROR,
    INVALID_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    ACCOUNT_FROZEN,
    EMAIL_NOT_SET,
    INVALID_RESET_TOKEN,
    TOO_MANY_REQUESTS,
    RATE_LIMIT_EXCEEDEG,
    OTP_ATTEMPTS_EXCEEDED,
    ACCOUNT_DELETED,
    WAS_FIRED,
    SMS_PROVIDER_ERROR,

    // Auth
    INVALID_PHONE,
    INVALID_PHONE_NUMBER,
    INVALID_CODE,
    CODE_EXPIRED,
    TOKEN_EXPIRED,
    USER_NOT_FOUND,
    CARD_IS_BLOCKED,
    USER_CREATION_FAILED,
    INVALID_PIN,
    WORKSPACE_ID_MISSING,

    // Business
    BUSINESS_ALREADY_EXISTS,
    BUSINESS_NOT_FOUND,
    POINT_NOT_FOUND,
    POINT_INACTIVE,
    POINT_PAUSED,
    ALREADY_JOINED,
    INVALID_INVITE_CODE,
    
    // Terminal
    QR_EXPIRED,
    INVALID_QR_SIGNATURE,
    SECURITY_QR_SECRET_MISSING,
    INVALID_AMOUNT,
    INVALID_TIER_VALUE,
    LOYALTY_SETTING_NOT_FOUND,
    CARD_NOT_FOUND,
    CARD_BLOCKED,
    CARD_PAUSED,
    TRIAL_ALREADY_USED,
    PARTNER_ON_REVIEW,
    PARTNER_BLOCKED,
    
    // Moderation
    USER_BANNED,
    BLOCK_REQUEST_CREATED,
    BLOCK_REQUEST_ALREADY_EXISTS,

    // Finance
    CURRENCY_RATE_NOT_FOUND
}


@Serializable
data class ApiMessage(
    val code: AppErrorCode,
    val message: String? = null
)
