import { writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { resources } from '../web-admin/src/i18n/resources.ts';
import { autoLanguages as existingAuto } from '../web-admin/src/i18n/autoLanguages.ts';

type FlatMap = Record<string, string>;

const TARGET_LANGS = (process.env.TARGET_LANGS ?? 'ky,kk,uz,be')
  .split(',')
  .map((lang) => lang.trim())
  .filter(Boolean);

const SKIP_TRANSLATION = process.env.DRY_RUN === '1';

const flatten = (input: Record<string, unknown>, prefix = '', acc: FlatMap = {}): FlatMap => {
  Object.entries(input).forEach(([key, value]) => {
    const nextKey = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      flatten(value as Record<string, unknown>, nextKey, acc);
    } else {
      acc[nextKey] = value === undefined || value === null ? '' : String(value);
    }
  });
  return acc;
};

const unflatten = (input: FlatMap) => {
  const result: Record<string, any> = {};
  Object.entries(input).forEach(([dotKey, value]) => {
    const parts = dotKey.split('.');
    let cursor = result;
    parts.forEach((part, idx) => {
      if (idx === parts.length - 1) {
        cursor[part] = value;
      } else {
        cursor[part] = cursor[part] ?? {};
        cursor = cursor[part];
      }
    });
  });
  return result;
};

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const PLACEHOLDER_REGEX = /{{\s*[^}]+\s*}}/g;
const BRAND_NAME = 'LoyaltyLoop';
const BRAND_TOKEN = '__LL_BRAND__';

const protectPlaceholders = (text: string) => {
  const matches = text.match(PLACEHOLDER_REGEX) ?? [];
  let protectedText = text.replace(new RegExp(BRAND_NAME, 'g'), BRAND_TOKEN);
  
  matches.forEach((placeholder, index) => {
    const token = `__LL_VAR_${index}__`;
    protectedText = protectedText.replace(placeholder, token);
  });
  return { protectedText, matches };
};

const restorePlaceholders = (text: string, placeholders: string[]) => {
  let restored = text;
  placeholders.forEach((placeholder, index) => {
    const token = new RegExp(`__LL_VAR_${index}__`, 'g');
    restored = restored.replace(token, placeholder);
  });
  return restored.replace(new RegExp(BRAND_TOKEN, 'g'), BRAND_NAME);
};

const translateText = async (text: string, target: string) => {
  if (SKIP_TRANSLATION || !text.trim()) {
    return text;
  }

  const { protectedText, matches } = protectPlaceholders(text);

  const params = new URLSearchParams({
    client: 'gtx',
    sl: 'ru',
    tl: target,
    dt: 't',
    q: protectedText,
  });

  const response = await fetch(`https://translate.googleapis.com/translate_a/single?${params.toString()}`);
  if (!response.ok) {
    throw new Error(`Failed to translate text. HTTP ${response.status}`);
  }
  const data = (await response.json()) as any;
  const translated = (data?.[0] ?? [])
    .map((segment: any[]) => segment?.[0] ?? '')
    .join('');

  await delay(250);

  return restorePlaceholders(translated, matches);
};

const run = async () => {
const ruFlat = flatten(resources.ru.translation);
const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..');
const outputDir = path.join(repoRoot, 'web-admin', 'src', 'i18n');
  const targetEntries: Record<string, { translation: Record<string, unknown> }> = {};

  for (const lang of TARGET_LANGS) {
    const existing = existingAuto[lang]?.translation ?? {};
    const workingFlat = { ...ruFlat, ...flatten(existing as Record<string, unknown>) };

    console.log(`Translating ${lang} (${Object.keys(ruFlat).length} keys)...`);

    for (const key of Object.keys(ruFlat)) {
      const currentValue = workingFlat[key];
      if (currentValue && currentValue !== ruFlat[key]) {
        continue;
      }

      try {
        workingFlat[key] = await translateText(ruFlat[key], lang);
      } catch (error) {
        console.error(`  ✖ Failed to translate key "${key}" for ${lang}: ${(error as Error).message}`);
        workingFlat[key] = ruFlat[key];
      }
    }

    targetEntries[lang] = { translation: unflatten(workingFlat) };
  }

  const autoFile = path.join(outputDir, 'autoLanguages.ts');
  const fileContent = `// This file is auto-generated by scripts/autoTranslate.ts
export const autoLanguages = ${JSON.stringify(targetEntries, null, 2)} as const;
`;
  writeFileSync(autoFile, fileContent, 'utf8');

  console.log(`Generated translations for: ${TARGET_LANGS.join(', ')}`);
  console.log(`Output: ${autoFile}`);
};

run().catch((error) => {
  console.error('Translation script failed:', error);
  process.exit(1);
});

